//Servicios
export const GET_SERVICIOS_SUCCESS = 'GET_SERVICIOS_SUCCESS';
export const ADD_SERVICIO_SUCCESS = 'ADD_SERVICIO_SUCCESS';
export const UPDATE_SERVICIO_SUCCESS = 'UPDATE_SERVICIO_SUCCESS';
export const DELETE_SERVICIO_SUCCESS = 'DELETE_SERVICIO_SUCCESS';

//Puestos
export const GET_PUESTOS_SUCCESS = 'GET_PUESTOS_SUCCESS';
export const ADD_PUESTO_SUCCESS = 'ADD_PUESTO_SUCCESS';
export const UPDATE_PUESTO_SUCCESS = 'UPDATE_PUESTO_SUCCESS';
export const DELETE_PUESTO_SUCCESS = 'DELETE_PUESTO_SUCCESS';

//Técnicos
export const GET_TECNICOS_SUCCESS = 'GET_TECNICOS_SUCCESS';
export const GET_PERSONALTECNICO_SUCCESS = 'GET_PERSONALTECNICO_SUCCESS';
export const ADD_TECNICO_SUCCESS = 'ADD_TECNICO_SUCCESS';
// export const UPDATE_TECNICO_SUCCESS = 'UPDATE_TECNICO_SUCCESS';
// export const DELETE_TECNICO_SUCCESS = 'DELETE_TECNICO_SUCCESS';
