//Servicios
export const GET_SERVICIOS_SUCCESS = 'GET_SERVICIOS_SUCCESS';
export const ADD_SERVICIOS_SUCCESS = 'ADD_SERVICIOS_SUCCESS';
export const UPDATE_SERVICIOS_SUCCESS = 'UPDATE_SERVICIOS_SUCCESS';
export const DELETE_SERVICIOS_SUCCESS = 'DELETE_SERVICIOS_SUCCESS';
