<?php

DEFINE('PERFIL_ADMINISTRADOR',1);
DEFINE('PERFIL_TECNICO_ADMIN',2);
DEFINE('PERFIL_TECNICO',3);
DEFINE('PERFIL_BASICO',4);

DEFINE('EQUIPO',1);
DEFINE('PRESTACION',2);

DEFINE('ESTADO_ALTA',1);
DEFINE('ESTADO_BAJA',9);

define("BASIC_PASSWORD",1234);